# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2api < Formula
  desc "The csv2api parser reads the CSV file with the raw data, filters the records, identifies fields to be changed, and sends a request to update the data to the specified endpoint of your REST API.
All actions take place according to the settings in the configuration file.
"
  homepage "https://github.com/koddr/csv2api"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koddr/csv2api/releases/download/v1.0.0/csv2api_1.0.0_darwin_arm64.tar.gz"
      sha256 "609bc56584ec34c3239b97c4e7da9916116fa19e00f278e0d220deda9b6b665c"

      def install
        bin.install "csv2api"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/csv2api/releases/download/v1.0.0/csv2api_1.0.0_darwin_amd64.tar.gz"
      sha256 "8bdf75b1ef8f39958c11e6fbbd9742612c4e6bf9b18289ed54749953cf916147"

      def install
        bin.install "csv2api"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koddr/csv2api/releases/download/v1.0.0/csv2api_1.0.0_linux_arm64.tar.gz"
      sha256 "db0df3ad58a2173c48ae2c281fae72df4d08f3221971ebb80df0008e6eba5b98"

      def install
        bin.install "csv2api"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/csv2api/releases/download/v1.0.0/csv2api_1.0.0_linux_amd64.tar.gz"
      sha256 "a83249c56d4c8ac81d89fa3cfc04d2ca9af576d95843cd12365d907f724597f0"

      def install
        bin.install "csv2api"
      end
    end
  end

  def caveats
    <<~EOS
      After install csv2api, run it with '-i' option to generate initial config.yml and data.csv files in the current dir:

      $ csv2api -i

      Prepare your config and input data files:

      In your config.yml:

      - Make sure that the first column name in the columns_order section is a primary key (PK) for your process.
      - Set up your API (base URL, token, endpoints, etc) in the api section.
      - Set up the filter for your fields in the filter_columns section.
      - Set up fields to be updated in the update_fields section.

      In your input data.csv:

      - Make sure that the first line of your CSV file contains the correct field names.

      💡 Note: See the repository's Wiki page (https://github.com/koddr/csv2api/wiki) to understand the structure of the config and input data files.

      And now, run csv2api with options:

      $ csv2api -c /path/to/config.yml -d /path/to/data.csv -e CONFIG

      Done! Your transactions have been performed.
    EOS
  end
end
