# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2csv < Formula
  desc "The parser can read given folder with *.json files, filtering and qualifying input data with intent & stop words dictionaries and save results to CSV files by given chunk size.
"
  homepage "https://github.com/koddr/json2csv"
  version "1.0.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_darwin_arm64.tar.gz"
      sha256 "6464871904522a6f790916af49828f06ec96627aa717532c598bf06fa596c5b2"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_darwin_amd64.tar.gz"
      sha256 "99bbdd09cf0bd732def34a6ddf84254cb8bb67d4008864b7800244982bb14e9d"

      def install
        bin.install "json2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_linux_arm64.tar.gz"
      sha256 "8b78fcf662476afab1c747f9b416543e72f57a0f188fbc3fd30537577ea1aca4"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_linux_amd64.tar.gz"
      sha256 "87a986c2860eb061267d8bb862863c7c977124f8cfbd9ca6888e089e20f3fc78"

      def install
        bin.install "json2csv"
      end
    end
  end

  def caveats
    <<~EOS
      After install json2csv, prepare folder with your data input in the *.json format, create JSON files with intents and filter.

      💡 Note: See the repository's Wiki page (https://github.com/koddr/json2csv/wiki) to understand structures of JSON files and get general recommendations for preparing the input data.

      Next, run json2csv parser with options:

      $ json2csv -json /path/to/input/json/folder -intents /path/to/intents-file.json -filter /path/to/filter-file.json -output /path/to/output/csv/folder -content-field message -min-word-len 5 -chunk 1000

      Done! Output CSV file(s) has a default comma (,) separators between columns.
    EOS
  end
end
