# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2csv < Formula
  desc "The parser can read given folder with *.json files, filtering and qualifying input data with intent & stop words dictionaries and save results to CSV files by given chunk size.
"
  homepage "https://github.com/koddr/json2csv"
  version "1.0.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_darwin_arm64.tar.gz"
      sha256 "b121286af94e874fc262111031922ff28097fe37db51e4ae276c5b5448972580"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_darwin_amd64.tar.gz"
      sha256 "7da54af096e4f41f965db92002f4452d7c2895e0d62d3d1a6391da56377ac941"

      def install
        bin.install "json2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_linux_amd64.tar.gz"
      sha256 "be8afe64d7196e2f48135a9c89fad33414c648cc119cc5b0a50e52ceaf7d502f"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.4/json2csv_1.0.4_linux_arm64.tar.gz"
      sha256 "a745cac18bb72a941754d82cd8a7be13588bfc9bae15d6a3026749f266e6db2b"

      def install
        bin.install "json2csv"
      end
    end
  end

  def caveats
    <<~EOS
      After install json2csv, prepare folder with your data input in the *.json format, create JSON files with intents and filter.

      💡 Note: See the repository's Wiki page (https://github.com/koddr/json2csv/wiki) to understand structures of JSON files and get general recommendations for preparing the input data.

      Next, run json2csv parser with options:

      $ json2csv -json /path/to/input/json/folder -intents /path/to/intents-file.json -filter /path/to/filter-file.json -output /path/to/output/csv/folder -content-field message -min-word-len 5 -chunk 1000

      Done! Output CSV file(s) has a default comma (,) separators between columns.
    EOS
  end
end
