# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2csv < Formula
  desc "The parser can read given folder with *.json files, filtering and qualifying input data with intent & stop words dictionaries and save results to CSV files by given chunk size.
"
  homepage "https://github.com/koddr/json2csv"
  version "1.0.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.2/json2csv_1.0.2_darwin_arm64.tar.gz"
      sha256 "7aacfb9ae18fb6af63b15cc8a82e9c4723874a17dda1a2b30a1793e2ed0a1a30"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.2/json2csv_1.0.2_darwin_amd64.tar.gz"
      sha256 "acfa76ec62c83175c2f8d831f014e6d95ee03dba3293b2513493f94226437672"

      def install
        bin.install "json2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.2/json2csv_1.0.2_linux_arm64.tar.gz"
      sha256 "f81d0e525d70cd417a228a494f56bd737c1c9855f6a9c0d65746baeb17e49cc1"

      def install
        bin.install "json2csv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/json2csv/releases/download/v1.0.2/json2csv_1.0.2_linux_amd64.tar.gz"
      sha256 "2c4255bf964a2a74938088aa2ca086e61d9d72a566de27e05a5bbc1895dc39c9"

      def install
        bin.install "json2csv"
      end
    end
  end

  def caveats
    <<~EOS
      After install json2csv, prepare folder with your data input in the *.json format, create JSON files with intents and filter.

      💡 Note: See the repository's Wiki page (https://github.com/koddr/json2csv/wiki) to understand structures of JSON files and get general recommendations for preparing the input data.

      Next, run json2csv parser with options:

      json2csv \
        -json    /path/to/input/json/folder \
        -intents /path/to/intents-file.json \
        -filter  /path/to/filter-file.json \
        -output  /path/to/output/csv/folder \
        -content-field message \
        -min-word-len  5 \
        -chunk 1000

      Done! Output CSV file(s) has a default comma (,) separators between columns.
    EOS
  end
end
