# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatr < Formula
  desc "Yet Another Task Runner (or yatr for a short) allows you to organize and automate your routine operations that you normally do in Makefile (or else) for each project.
"
  homepage "https://github.com/koddr/yatr"
  version "1.2.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koddr/yatr/releases/download/v1.2.0/yatr_1.2.0_darwin_arm64.tar.gz"
      sha256 "35eca9e23c35bb75e3c8be32ba664147b986ccb45580457e4d4e1ec4621ce34c"

      def install
        bin.install "yatr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/yatr/releases/download/v1.2.0/yatr_1.2.0_darwin_amd64.tar.gz"
      sha256 "5050e8a7d4d4bb87e0faf2dd6f6231173fd05d1c4d1e7e9d9525fa8fdbb53cbe"

      def install
        bin.install "yatr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koddr/yatr/releases/download/v1.2.0/yatr_1.2.0_linux_arm64.tar.gz"
      sha256 "bdc8baab7cb34bf2e60de4d4919c7dfa1ae8d9915b2471d40af5b840165ba0d4"

      def install
        bin.install "yatr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koddr/yatr/releases/download/v1.2.0/yatr_1.2.0_linux_amd64.tar.gz"
      sha256 "f820c990597f28ab9d79ac4d53bb6b1b4ca9591990f59bf7dad8cca70a8d320a"

      def install
        bin.install "yatr"
      end
    end
  end

  def caveats
    <<~EOS
      After install, run yatr with -i option for generate initial tasks.yml file in the current dir:

      $ yatr -i

      Prepare your task file in one of the supported formats: JSON, YAML, TOML, or HCL (Terraform).

      💡 Note: See the repository's Wiki page (https://github.com/koddr/yatr/wiki) to understand structure of the task file.

      And now, run yatr with options:

      $ yatr -p ./path/to/tasks.yml

      Done! Your tasks have been executed.
    EOS
  end
end
